site_name: ISWAT - International Space Weather Action Teams 
site_description: Webpage for the ISWAT Action Team S2-06 Meeting in Oslo

nav:
  - Home: index.md
  - Schedule: schedule.md
  - Venue: venue.md

theme:
  name: 'material'
  logo: false
  font: false
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  palette:
    - scheme: default
      primary: custom
      accent: light blue

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
